name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 100.53.12.150
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/united-seat-service
            git pull origin main
            sudo systemctl stop seatapp
            if [ -f app.py ]; then
              sudo systemctl start seatapp
              echo "App started"
            else
              echo "No app.py — service stopped"
            fi
