name: Reset Demo Environment

on:
  workflow_dispatch:

jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - name: Reset EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: 100.53.12.150
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            sudo systemctl disable seatapp
            sudo systemctl stop seatapp
            pkill -f "python3 app.py" || true
            cd ~/united-seat-service
            git fetch origin main
            git reset --hard origin/main
            sleep 1
            echo "App stopped and repo reset"
